### ISSUE TITLE
User Specific Data

### ISSUE THREAD

**Issue by tomlamensia** [FlySolutions/FK-AKAMAI-SOLUTIONS#1]
Hi! I had a question regarding the user generated data. I believe it is collected locally and sent to the endpoint "/bootstrap/1". How does one generate such data?

`const data = {
        fcrp: req.body.fcrp,
        ua: req.body.ua,
        psub: req.body.psub,
        np: req.body.np,
        bd1: req.body.bd1,
        fas1: req.body.fas1,
        gd1: req.body.gd1,
        prod: req.body.prod,
        automation: req.body.automation,
        mouseRes: req.body.mouseRes,
        xagg: req.body.xagg,
        dm: req.body.dm,
        c3: req.body.c3,
        mr: req.body.mr,
        fpvalstr: req.body.fpvalstr,
        webglRender: req.body.webglRender
    }`

**Comment by FlySolutions** [comment]
sorry, i will not be helping any one with the script.
